services:
  redis:
    image: redis:7
    container_name: redis_app
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
      - 6379:6379

  app:
    image: library_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy

volumes:
  db-data: